### ISSUE TITLE
Screen option is not displaying

### ISSUE THREAD

**Issue by Praline001** [explodybits/hookr-plugin#2]
Hello,
Thanks for this great plugin, I've just found a little bug.
When the plugin is active, we can't access to the screen options.
Have a good day,
Aude.

**Comment by explodybits** [comment]
The screen options can be accessed by either clicking the "Hookr" logo in
the admin bar, or under the Admin "Tools" in the lefthand menu.

**Comment by Praline001** [comment]
Hi, 
In fact, I was talking about the Wordpress Screen Option when we are in post or page edit screen.
Regards.
Aude

**Comment by explodybits** [comment]
I will look into this.
