### ISSUE TITLE
Enable only with a parameter in url

### ISSUE THREAD

**Issue by Mte90** [explodybits/hookr-plugin#3]
I think that have hookr enabled in all the pages can be useless but a parameter in URL can simplify that.
In the url something like domain.tld/?hookr=1

**Comment by credwards27** [comment]
I'll second this, maybe even with a toggle in the admin bar.

**Comment by explodybits** [comment]
You can enable/disable from the admin bar "Hookr" dropdown-- isnt that the
same thing?

**Comment by Mte90** [comment]
well for that I go to the hookr settings page and after change the settings but a simple way for reduce the number of step for that?

**Comment by explodybits** [comment]
But that is what im saying-- if the plugin is activated, and you have the
admin bar enabled as part of your user profile, there will be the Hookr
logo as a button in the admin bar. When you hover over this button, a drop
down will appear with two items: a search box and an Enable/Disable option.

You can keep it disabled when you dont want to run a trace, then enable it
when you are ready. This accomplishes what you are after, unless Im
misunderstanding what you are after :)

**Comment by Mte90** [comment]
i have downloaded the last version and is missing the enable/disable option in the dropdown menu

**Comment by explodybits** [comment]
It wont show the dropdown when you are on the hookr settings page-- please
advise. If you still arent seeing it appear on other admin pages, or
anywhere on the frontend, please let me know what version of WP you are
running. Screenshots might help too.
